services:
  - type: web
    name: telegram-otp-bot
    env: docker
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_bot_token_here
      - key: DATABASE_URL
        value: postgresql://user:pass@host:port/dbname
